trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    backendType: 'azurerm'
    backendServiceArm: 'azure-service-connection'
    backendAzureRmResourceGroupName: 'k8s-rg'
    backendAzureRmStorageAccountName: 'k8sstorageaccnt'
    backendAzureRmContainerName: 'k8scontainer'
    backendAzureRmKey: 'k8s.key'

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'azure-service-connection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'